import { useRouter } from "next/router"
import { useQuery } from '@apollo/client'
import { GET_LAUNCHES } from '../../graphql/queries'
import {MDBCarousel,MDBCarouselInner,MDBCarouselItem,MDBCarouselElement,MDBCarouselCaption,} from 'mdb-react-ui-kit';
import Head from "next/head";

function LaunchesDetails() {
    const router = useRouter();
    const {id} = router.query;

    const {loading,error,data} = useQuery(GET_LAUNCHES);
    if (loading) {
      return "loading";
    }
    if (error) {
      return "error";
    }
    const launches = data.launchesPast.filter(
      (launch) => launch.id === id
    );

    console.log(launches)
    
    return (
        <>
        <Head>
          <title>{launches[0].mission_name} | Details</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" rel="stylesheet" />
        </Head>

         <MDBCarousel showIndicators showControls fade>
            <MDBCarouselInner>
              <MDBCarouselItem  className='active post'>
                <MDBCarouselElement src={launches[0].links.flickr_images[0]} alt='...' />
                <MDBCarouselCaption className="post-text">
                  <h5>{launches[0].mission_name}</h5>
                  <p>{launches[0].details}</p>
                </MDBCarouselCaption>
              </MDBCarouselItem>

              {launches[0].links.flickr_images.slice(1,3).map((image_url)=>(
                <MDBCarouselItem className="post">
                <MDBCarouselElement src={image_url} alt='...' />
                <MDBCarouselCaption className="post-text">
                  <h5>{launches[0].mission_name}</h5>
                  <p>{launches[0].details}</p>
                </MDBCarouselCaption>
              </MDBCarouselItem>
              ) )}
            </MDBCarouselInner>
          </MDBCarousel>
        </>


    )
}
export default LaunchesDetails