import { useRouter } from "next/router"
import { useQuery } from '@apollo/client'
import { GET_LAUNCH_BYID } from '../../graphql/queries'
import {MDBCarousel,MDBCarouselInner,MDBCarouselItem,MDBCarouselElement,MDBCarouselCaption,} from 'mdb-react-ui-kit';
import Head from "next/head";

function LaunchesDetails() {
    const router = useRouter();
    const {id} = router.query;

    const {loading,error,data} = useQuery(GET_LAUNCH_BYID,{
      variables: { id },
    });

    if (loading) {
      return "loading";
    }
    if (error) {
      return "error";
    }
 
    return (
        <>
        <Head>
          <title>{data.launch.mission_name} | Details</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" rel="stylesheet" />
        </Head>

         <MDBCarousel showIndicators showControls fade>
            <MDBCarouselInner>

              <MDBCarouselItem  className='active post'>
                <MDBCarouselElement src={data.launch.links.flickr_images[0]} alt='...' />
              </MDBCarouselItem>

              {data.launch.links.flickr_images.slice(1,3).map((image_url,index)=>(
                <MDBCarouselItem className="post" key={index}>
                  <MDBCarouselElement src={image_url} alt='...' />
                </MDBCarouselItem>
              ))}
            </MDBCarouselInner>
          </MDBCarousel>

          <div className="details text-center  p-5">
                  <h1>{data.launch.mission_name}</h1>
                  <p>{data.launch.details}</p>
          </div>
        </>


    )
}
export default LaunchesDetails